version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production

  client:
    build:
      context: ./client
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  nginx:
    build:
      context: .
    ports:
      - '80:80'
    depends_on:
      - client
      - server
