import type { Metadata } from "next";
import Provider from "./provider";
import "./globals.css";
import { Lexend_Exa } from 'next/font/google'
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import ContextsProvider from "@/providers/contextsProvider";

export const metadata: Metadata = {
  title: "Online Pharmacy",
  description: "Generated by create next app",
};

const LexendExa = Lexend_Exa({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={LexendExa.className}>
      <body
      >
        <Header />
        <ContextsProvider>
          <Provider>
            {children}
          </Provider>
        </ContextsProvider>
        <Footer />
      </body>
    </html>
  );
}
